//
// This source file is part of the Stanford Biodesign Digital Health Spezi Firebase Remote Notifications open-source project
//
// SPDX-FileCopyrightText: 2025 Stanford University
//
// SPDX-License-Identifier: MIT
//

import {
  addressSchema,
  annotationSchema,
  attachmentSchema,
  backboneElementSchema,
  base64BinarySchema,
  booleanSchema,
  canonicalSchema,
  codeableConceptSchema,
  codeSchema,
  codingSchema,
  contactDetailSchema,
  contactPointSchema,
  contributorSchema,
  dataRequirementSchema,
  dateSchema,
  dateTimeSchema,
  decimalSchema,
  dosageSchema,
  elementSchema,
  expressionSchema,
  humanNameSchema,
  identifierSchema,
  idSchema,
  instantSchema,
  intSchema,
  markdownSchema,
  metaSchema,
  moneySchema,
  oidSchema,
  parameterDefinitionSchema,
  periodSchema,
  positiveIntSchema,
  quantitySchema,
  rangeSchema,
  ratioSchema,
  referenceSchema,
  relatedArtifactSchema,
  sampledDataSchema,
  signatureSchema,
  stringSchema,
  timeSchema,
  timingSchema,
  triggerDefinitionSchema,
  unsignedIntSchema,
  uriSchema,
  urlSchema,
  usageContextSchema,
  uuidSchema,
} from './index.js'

/**
 * Zod schema for FHIR elements with value[x] fields supporting any FHIR data type.
 */
export const anyValueSchema = backboneElementSchema.extend({
  valueBase64Binary: base64BinarySchema.optional(),
  _valueBase64Binary: elementSchema.optional(),
  valueBoolean: booleanSchema.optional(),
  _valueBoolean: elementSchema.optional(),
  valueCanonical: canonicalSchema.optional(),
  _valueCanonical: elementSchema.optional(),
  valueCode: codeSchema.optional(),
  _valueCode: elementSchema.optional(),
  valueDate: dateSchema.optional(),
  _valueDate: elementSchema.optional(),
  valueDateTime: dateTimeSchema.optional(),
  _valueDateTime: elementSchema.optional(),
  valueDecimal: decimalSchema.optional(),
  valueId: idSchema.optional(),
  _valueId: elementSchema.optional(),
  valueInstant: instantSchema.optional(),
  _valueInstant: elementSchema.optional(),
  valueInteger: intSchema.optional(),
  valueMarkdown: markdownSchema.optional(),
  _valueMarkdown: elementSchema.optional(),
  valueOid: oidSchema.optional(),
  _valueOid: elementSchema.optional(),
  valuePositiveInt: positiveIntSchema.optional(),
  valueString: stringSchema.optional(),
  _valueString: elementSchema.optional(),
  valueTime: timeSchema.optional(),
  _valueTime: elementSchema.optional(),
  valueUnsignedInt: unsignedIntSchema.optional(),
  valueUri: uriSchema.optional(),
  _valueUri: elementSchema.optional(),
  valueUrl: urlSchema.optional(),
  _valueUrl: elementSchema.optional(),
  valueUuid: uuidSchema.optional(),
  _valueUuid: elementSchema.optional(),
  valueAddress: addressSchema.optional(),
  valueAge: quantitySchema.optional(),
  valueAnnotation: annotationSchema.optional(),
  valueAttachment: attachmentSchema.optional(),
  valueCodeableConcept: codeableConceptSchema.optional(),
  valueCoding: codingSchema.optional(),
  valueContactPoint: contactPointSchema.optional(),
  valueCount: quantitySchema.optional(),
  valueDistance: quantitySchema.optional(),
  valueDuration: quantitySchema.optional(),
  valueHumanName: humanNameSchema.optional(),
  valueIdentifier: identifierSchema.optional(),
  valueMoney: moneySchema.optional(),
  valuePeriod: periodSchema.optional(),
  valueQuantity: quantitySchema.optional(),
  valueRange: rangeSchema.optional(),
  valueRatio: ratioSchema.optional(),
  valueReference: referenceSchema.optional(),
  valueSampledData: sampledDataSchema.optional(),
  valueSignature: signatureSchema.optional(),
  valueTiming: timingSchema.optional(),
  valueContactDetail: contactDetailSchema.optional(),
  valueContributor: contributorSchema.optional(),
  valueDataRequirement: dataRequirementSchema.optional(),
  valueExpression: expressionSchema.optional(),
  valueParameterDefinition: parameterDefinitionSchema.optional(),
  valueRelatedArtifact: relatedArtifactSchema.optional(),
  valueTriggerDefinition: triggerDefinitionSchema.optional(),
  valueUsageContext: usageContextSchema.optional(),
  valueDosage: dosageSchema.optional(),
  valueMeta: metaSchema.optional(),
})
