#
# This source file is part of the Stanford Biodesign Digital Health Spezi Firebase open-source project
#
# SPDX-FileCopyrightText: 2024 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Deployment

on:
  release:
    types: [published]
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: production
  cancel-in-progress: false

jobs:
  build-and-test:
    name: Build and Test
    uses: ./.github/workflows/build-and-test.yml
    permissions:
      contents: read
      checks: write
      actions: read
      security-events: write
    secrets: inherit
  publishpackage:
    name: Publish Package
    needs: build-and-test
    uses: StanfordBDHG/.github/.github/workflows/npm-publish-package.yml@main
    permissions:
      contents: read
      id-token: write
      packages: write
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      packageVersion: ${{ github.event.release.tag_name }}
      workspace: true